### ISSUE TITLE
how to keep the Drone inital status?

### ISSUE THREAD

**Issue by BigRabbit** [felixge/node-ar-drone#120]
hi, when the drone is hovering in the air, I use node-ar-drone to connect  it,  then it will land on the ground. how can I put the drone in the previous status, not to land on the ground?

**Comment by wiseman** [comment]
One thing you could try is in the [`resume`](https://github.com/felixge/node-ar-drone/blob/master/lib/Client.js#L93) method, set `_ref.fly = true` so that the client will immediately start sending the drone the right commands to stay in the air. (You can see an example in the [`takeoff`](https://github.com/felixge/node-ar-drone/blob/master/lib/Client.js#L193) command.)
